In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset =pd.read_csv('insurance_pre.csv')
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
indep=dataset[['age','bmi','children','sex_male','smoker_yes']]

In [6]:
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(indep, dep, test_size = 0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [10]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared error','absolute error', 'poisson'],
              'max_features': ['sqrt','log2'],
              'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared error', 'absolute error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [11]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 100}: 0.8676757973157239

In [12]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001797,0.000321,0.000000,0.000000,squared error,sqrt,10,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,0.001670,0.000315,0.000000,0.000000,squared error,sqrt,100,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,0.001081,0.000299,0.000000,0.000000,squared error,log2,10,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.000983,0.000095,0.000000,0.000000,squared error,log2,100,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,0.001079,0.000254,0.000000,0.000000,absolute error,sqrt,10,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,0.001015,0.000354,0.000000,0.000000,absolute error,sqrt,100,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
6,0.000927,0.000131,0.000000,0.000000,absolute error,log2,10,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
7,0.000969,0.000033,0.000000,0.000000,absolute error,log2,100,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
8,0.042534,0.002099,0.003994,0.000483,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.832334,0.770489,0.787272,0.782755,0.744413,0.783453,0.028624,4
9,0.401894,0.006389,0.016320,0.001525,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.862602,0.782184,0.810561,0.825887,0.771615,0.810570,0.032451,2
10,0.041592,0.001588,0.003533,0.000764,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.844673,0.770500,0.758378,0.807421,0.757797,0.787754,0.033719,3
11,0.371193,0.008497,0.013409,0.001448,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.862367,0.795111,0.811498,0.825106,0.772252,0.813267,0.030219,1

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 28
BMI: 33
Children: 3
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[17259.6071439]